### ISSUE TITLE
Different units for intakes

### ISSUE THREAD

**Issue by qligier** [CARA-ch/pmp-issues#39]
Should different units for intakes be a supported use case?
E.g. 2 tablets in the morning, and 50mg in the evening.

**Comment by dvribeira** [comment]
@qligier I have just bumped into this issue by chance. Out of curiosity first, do you happen to have an actual use case / example / request for this?

**Comment by qligier** [comment]
I don't have any use case or request for that. It's technically allowed by the exchange format, but I'm unsure if there is any reason to support it.
The web portal doesn't currently support it.

**Comment by dvribeira** [comment]
@qligier I can confirm that neither Swissmeds nor Presco support it either. We can bring the subject on the next pmp specs meeting.

**Comment by qligier** [comment]
Thanks for asking them! I won't be present at the meeting this afternoon, but Oliver will attend.

**Comment by dvribeira** [comment]
Soarian seems to support this, in principle, depending on the set up of the physical units table. For instance, users would normally be allowed to mix `g` and `mg` on the same order, or `goutte` and `mL` for another but it can get even trickier. Regarding export/import from/to Soarian to/from the PMP, it seems export worked on the tests they performed and not import, this is probably not a thoroughly tested feature, since most likely it is not often used by practitioners, if at all.

On top of that, and as additional piece of info to be considered, eMediplan has a different model for which strictly speaking a dosage can have only one unit, but in turn a medication within a plan can have several dosages (with possibly different periods, so it would actually translate to different medication statements to us) making it possible in practice. Thus, in the [FHIR translation of the eMediplan](https://chmed20af.emediplan.ch) it is possible to use a split dosage with different units but also different boundsPeriod, which we do not allow. The way to go, without changing CH EMED EPR for this, to support also different periods, would be to consider each eMediplan (not FHIR) posology object a different medication statement: this in turn would mean that our translation of eMediplan would not allow for different units per statement, as one posology object can have only one unit. This would need more thought, since it might not be OK to do that for prescriptions.

**Comment by dvribeira** [comment]
Feedback from L-Z. Kaestli: not to be supported.
Still waiting for professional feedback from CHUV.

**Comment by dvribeira** [comment]
Finally received some feedback from F. Bastardot (CHUV). He considers the possibility as confusing and potentially dangerous and not to be supported.

@qligier  Unless you have something against it or you'd like to get this validated by the COPIL, I will go ahead (not necessarily right away) and address this in the [CH EMED EPR issue](https://github.com/CARA-ch/ch-emed-epr/issues/75)

**Comment by qligier** [comment]
Thank you for collecting the feedbacks. I agree we should move on and implement this restriction.

**Comment by dvribeira** [comment]
Implemented for CH EMED EPR 2.0.0
